# 2ND DAY PANDAS

In [12]:
import pandas as pd

data = {
    "mobile": ["A", "B", "C"],
    "battery_size": [4000, None, 5000]
}

df = pd.DataFrame(data)

df = df.dropna(subset=['battery_size'])
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2 entries, 0 to 2
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mobile        2 non-null      str
 1   battery_size  2 non-null      float64
dtypes: float64(1), str(1)
memory usage: 164.0 bytes

In [13]:
df = pd.read_csv("Mobile_data.csv")
df.isnull().sum()

Unnamed: 0          0
brand_name          0
model_name          0
os                197
popularity          0
best_price          0
lowest_price      260
highest_price     260
sellers_amount      0
screen_size         2
memory_size       112
battery_size       10
release_date        0
dtype: int64

In [14]:
df.isnull().sum()
df.duplicated().sum()
df.drop_duplicates()

,Unnamed: 0,brand_name,model_name,os,popularity,best_price,lowest_price,highest_price,sellers_amount,screen_size,memory_size,battery_size,release_date
0,0,ALCATEL,1 1/8GB Bluish Black (5033D-2JALUAA),Android,422,1690,1529.0,1819.0,36,5.00,8.0,2000.0,20-Oct
1,1,ALCATEL,1 5033D 1/16GB Volcano Black (5033D-2LALUAF),Android,323,1803,1659.0,2489.0,36,5.00,16.0,2000.0,20-Sep
2,2,ALCATEL,1 5033D 1/16GB Volcano Black (5033D-2LALUAF),Android,299,1803,1659.0,2489.0,36,5.00,16.0,2000.0,20-Sep
3,3,ALCATEL,1 5033D 1/16GB Volcano Black (5033D-2LALUAF),Android,287,1803,1659.0,2489.0,36,5.00,16.0,2000.0,20-Sep
4,4,Nokia,1.3 1/16GB Charcoal,Android,1047,1999,NaN,NaN,10,5.71,16.0,3000.0,20-Apr
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1219,1219,Apple,iPhone XS Max 64GB Gold (MT522),iOS,1101,22685,16018.0,27900.0,61,6.50,64.0,3174.0,18-Sep
1220,1220,Apple,iPhone XS Max Dual Sim 64GB Gold (MT732),iOS,530,24600,21939.0,33720.0,28,6.50,64.0,3174.0,18-Sep
1221,1221,HUAWEI,nova 5T 6/128GB Black (51094MEU),Android,1174,8804,7999.0,9999.0,18,6.26,128.0,3750.0,19-Nov
1222,1222,ZTE,nubia Red Magic 5G 8/128GB Black,Android,752,18755,18500.0,19010.0,2,6.65,128.0,4500.0,20-Oct
1223,1223,Sigma mobile,x-style 35 Screen,NaN,952,907,785.0,944.0,75,3.50,NaN,1750.0,20-Jan

In [15]:
x = df['highest_price'].mean()
newdf= df.fillna(x)
newdf.info()
newdf.head(10)

<class 'pandas.DataFrame'>
RangeIndex: 1224 entries, 0 to 1223
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      1224 non-null   int64
 1   brand_name      1224 non-null   str
 2   model_name      1224 non-null   str
 3   os              1224 non-null   object
 4   popularity      1224 non-null   int64
 5   best_price      1224 non-null   int64
 6   lowest_price    1224 non-null   float64
 7   highest_price   1224 non-null   float64
 8   sellers_amount  1224 non-null   int64
 9   screen_size     1224 non-null   float64
 10  memory_size     1224 non-null   float64
 11  battery_size    1224 non-null   float64
 12  release_date    1224 non-null   str
dtypes: float64(5), int64(4), object(1), str(3)
memory usage: 124.4+ KB

,Unnamed: 0,brand_name,model_name,os,popularity,best_price,lowest_price,highest_price,sellers_amount,screen_size,memory_size,battery_size,release_date
0,0,ALCATEL,1 1/8GB Bluish Black (5033D-2JALUAA),Android,422,1690,1529.000000,1819.000000,36,5.00,8.0,2000.0,20-Oct
1,1,ALCATEL,1 5033D 1/16GB Volcano Black (5033D-2LALUAF),Android,323,1803,1659.000000,2489.000000,36,5.00,16.0,2000.0,20-Sep
2,2,ALCATEL,1 5033D 1/16GB Volcano Black (5033D-2LALUAF),Android,299,1803,1659.000000,2489.000000,36,5.00,16.0,2000.0,20-Sep
3,3,ALCATEL,1 5033D 1/16GB Volcano Black (5033D-2LALUAF),Android,287,1803,1659.000000,2489.000000,36,5.00,16.0,2000.0,20-Sep
4,4,Nokia,1.3 1/16GB Charcoal,Android,1047,1999,9883.410788,9883.410788,10,5.71,16.0,3000.0,20-Apr
5,5,Honor,10 6/64GB Black,Android,71,10865,10631.000000,11099.000000,2,5.80,64.0,3400.0,18-Jun
6,6,Honor,10 Lite 3/32GB Blue,Android,424,3999,9883.410788,9883.410788,2,6.21,32.0,3400.0,18-Dec
7,7,Honor,10 Lite 4/64GB Black,Android,134,4973,4733.000000,5295.000000,6,6.21,64.0,3400.0,19-Jan
8,8,Honor,10 lite 3/128GB Blue,Android,477,5100,4990.000000,5222.000000,3,6.21,128.0,3400.0,21-Jan
9,9,Honor,10 lite 3/64GB Black,Android,215,4948,4646.000000,5372.000000,8,6.21,64.0,3400.0,18-Dec

In [16]:
# df["highest_price"]=df.fillna(["highest_price"]).mean()
df = df.fillna(x)
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1224 entries, 0 to 1223
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      1224 non-null   int64
 1   brand_name      1224 non-null   str
 2   model_name      1224 non-null   str
 3   os              1224 non-null   object
 4   popularity      1224 non-null   int64
 5   best_price      1224 non-null   int64
 6   lowest_price    1224 non-null   float64
 7   highest_price   1224 non-null   float64
 8   sellers_amount  1224 non-null   int64
 9   screen_size     1224 non-null   float64
 10  memory_size     1224 non-null   float64
 11  battery_size    1224 non-null   float64
 12  release_date    1224 non-null   str
dtypes: float64(5), int64(4), object(1), str(3)
memory usage: 124.4+ KB

In [17]:
df["highest_price"]=df["highest_price"].fillna(
    df.groupby('brand_name')['highest_price'].transform('mean'))
df.info()
df.head(10)

<class 'pandas.DataFrame'>
RangeIndex: 1224 entries, 0 to 1223
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      1224 non-null   int64
 1   brand_name      1224 non-null   str
 2   model_name      1224 non-null   str
 3   os              1224 non-null   object
 4   popularity      1224 non-null   int64
 5   best_price      1224 non-null   int64
 6   lowest_price    1224 non-null   float64
 7   highest_price   1224 non-null   float64
 8   sellers_amount  1224 non-null   int64
 9   screen_size     1224 non-null   float64
 10  memory_size     1224 non-null   float64
 11  battery_size    1224 non-null   float64
 12  release_date    1224 non-null   str
dtypes: float64(5), int64(4), object(1), str(3)
memory usage: 124.4+ KB

,Unnamed: 0,brand_name,model_name,os,popularity,best_price,lowest_price,highest_price,sellers_amount,screen_size,memory_size,battery_size,release_date
0,0,ALCATEL,1 1/8GB Bluish Black (5033D-2JALUAA),Android,422,1690,1529.000000,1819.000000,36,5.00,8.0,2000.0,20-Oct
1,1,ALCATEL,1 5033D 1/16GB Volcano Black (5033D-2LALUAF),Android,323,1803,1659.000000,2489.000000,36,5.00,16.0,2000.0,20-Sep
2,2,ALCATEL,1 5033D 1/16GB Volcano Black (5033D-2LALUAF),Android,299,1803,1659.000000,2489.000000,36,5.00,16.0,2000.0,20-Sep
3,3,ALCATEL,1 5033D 1/16GB Volcano Black (5033D-2LALUAF),Android,287,1803,1659.000000,2489.000000,36,5.00,16.0,2000.0,20-Sep
4,4,Nokia,1.3 1/16GB Charcoal,Android,1047,1999,9883.410788,9883.410788,10,5.71,16.0,3000.0,20-Apr
5,5,Honor,10 6/64GB Black,Android,71,10865,10631.000000,11099.000000,2,5.80,64.0,3400.0,18-Jun
6,6,Honor,10 Lite 3/32GB Blue,Android,424,3999,9883.410788,9883.410788,2,6.21,32.0,3400.0,18-Dec
7,7,Honor,10 Lite 4/64GB Black,Android,134,4973,4733.000000,5295.000000,6,6.21,64.0,3400.0,19-Jan
8,8,Honor,10 lite 3/128GB Blue,Android,477,5100,4990.000000,5222.000000,3,6.21,128.0,3400.0,21-Jan
9,9,Honor,10 lite 3/64GB Black,Android,215,4948,4646.000000,5372.000000,8,6.21,64.0,3400.0,18-Dec

In [18]:
# df["highest_price"]=df["highest_price"].fillna(df['highest_price'].mean())
df["lowest_price"]=df["lowest_price"].fillna(df['lowest_price'].mean())

df.info()
# df.head(10)

<class 'pandas.DataFrame'>
RangeIndex: 1224 entries, 0 to 1223
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      1224 non-null   int64
 1   brand_name      1224 non-null   str
 2   model_name      1224 non-null   str
 3   os              1224 non-null   object
 4   popularity      1224 non-null   int64
 5   best_price      1224 non-null   int64
 6   lowest_price    1224 non-null   float64
 7   highest_price   1224 non-null   float64
 8   sellers_amount  1224 non-null   int64
 9   screen_size     1224 non-null   float64
 10  memory_size     1224 non-null   float64
 11  battery_size    1224 non-null   float64
 12  release_date    1224 non-null   str
dtypes: float64(5), int64(4), object(1), str(3)
memory usage: 124.4+ KB

In [19]:
df.dropna(subset=['os'])
# df.head(10)
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1224 entries, 0 to 1223
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      1224 non-null   int64
 1   brand_name      1224 non-null   str
 2   model_name      1224 non-null   str
 3   os              1224 non-null   object
 4   popularity      1224 non-null   int64
 5   best_price      1224 non-null   int64
 6   lowest_price    1224 non-null   float64
 7   highest_price   1224 non-null   float64
 8   sellers_amount  1224 non-null   int64
 9   screen_size     1224 non-null   float64
 10  memory_size     1224 non-null   float64
 11  battery_size    1224 non-null   float64
 12  release_date    1224 non-null   str
dtypes: float64(5), int64(4), object(1), str(3)
memory usage: 124.4+ KB

# Convert datatype

In [20]:
df['lowest_price'] =df['lowest_price'].astype(int)
df['release_date'] = pd.to_datetime(df['release_date'])
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1224 entries, 0 to 1223
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      1224 non-null   int64
 1   brand_name      1224 non-null   str
 2   model_name      1224 non-null   str
 3   os              1224 non-null   object
 4   popularity      1224 non-null   int64
 5   best_price      1224 non-null   int64
 6   lowest_price    1224 non-null   int64
 7   highest_price   1224 non-null   float64
 8   sellers_amount  1224 non-null   int64
 9   screen_size     1224 non-null   float64
 10  memory_size     1224 non-null   float64
 11  battery_size    1224 non-null   float64
 12  release_date    1224 non-null   datetime64[us]
dtypes: datetime64[us](1), float64(4), int64(5), object(1), str(2)
memory usage: 124.4+ KB

C:\Users\DELL\AppData\Local\Temp\ipykernel_6012\2239762225.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['release_date'] = pd.to_datetime(df['release_date'])

# Renaming columns

In [22]:
d = df.rename(columns={'batter_size': 'date'})
d.head()
# d.info()

,Unnamed: 0,brand_name,model_name,os,popularity,best_price,lowest_price,highest_price,sellers_amount,screen_size,memory_size,battery_size,release_date
0,0,ALCATEL,1 1/8GB Bluish Black (5033D-2JALUAA),Android,422,1690,1529,1819.000000,36,5.00,8.0,2000.0,1-10-20
1,1,ALCATEL,1 5033D 1/16GB Volcano Black (5033D-2LALUAF),Android,323,1803,1659,2489.000000,36,5.00,16.0,2000.0,1-09-20
2,2,ALCATEL,1 5033D 1/16GB Volcano Black (5033D-2LALUAF),Android,299,1803,1659,2489.000000,36,5.00,16.0,2000.0,1-09-20
3,3,ALCATEL,1 5033D 1/16GB Volcano Black (5033D-2LALUAF),Android,287,1803,1659,2489.000000,36,5.00,16.0,2000.0,1-09-20
4,4,Nokia,1.3 1/16GB Charcoal,Android,1047,1999,9883,9883.410788,10,5.71,16.0,3000.0,1-04-20